js_StringTable = new Array();

js_StringTable["ACTIONS_TITLE"] = "Actions";
js_StringTable["SEARCH"] = "Search";
js_StringTable["SEARCH_H"] = "Find studies in the remote backend";
js_StringTable["SETTINGS"] = "Basic settings";
js_StringTable["SETTINGS_H"] = "Configure basic parameters";
js_StringTable["ABOUT"] = "About";
js_StringTable["ABOUT_H"] = "RemotEye Lite information";
js_StringTable["ABOUT_DEV"] = "Developed by NeoLogica";
js_StringTable["READ_BEF_USE"] = "Please read the User Manual before use";
js_StringTable["BACK"] = "Back";
js_StringTable["FIND_PAGE_TITLE"] = "Studies";
js_StringTable["SHOW_FILTER"] = "Show filter";
js_StringTable["STUDIES_FOUND"] = "Page";
js_StringTable["PATIENT_NAME"] = "Patient Name";
js_StringTable["STUDY_DATE"] = "Study date";
js_StringTable["STUDY_DESCR"] = "Study descr.";
js_StringTable["SERIES_FOUND"] = "Series found";
js_StringTable["SERIES_DESCR"] = "Series descr.";
js_StringTable["PATIENT_SEX"] = "Patient sex";
js_StringTable["PATIENT_BD"] = "Patient birthdate";
js_StringTable["NUM_OF_FRAME"] = "Number of frames";
js_StringTable["STUDY_DATE_START"] = "Examined after";
js_StringTable["STUDY_DATE_END"] = "Examined before";
js_StringTable["PANELS_LAYOUT"] = "Image panels layout";
js_StringTable["ROWS"] = "Rows";
js_StringTable["COLS"] = "Columns";
js_StringTable["CANCEL"] = "Cancel";
js_StringTable["SAVE"] = "Save";
js_StringTable["ACCEPT"] = "Accept";
js_StringTable["PREVIOUS"] = "Previous";
js_StringTable["NEXT"] = "Next";
js_StringTable["TODAY"] = "Today";
js_StringTable["LAST_WEEK"] = "Last week";
js_StringTable["LAST_MONTH"] = "Last month";
js_StringTable["WHENEVER"] = "Any date";

js_StringTable["DISCLAIMER"] = "This software module is NOT intended for diagnostic usage";
js_StringTable["INV_LIC"] = "Invalid License";
js_StringTable["COMM_ERR"] = "Communication Error";
js_StringTable["INV_LOG"] = "Invalid Login";

js_StringTable['DEF_FPS'] = "Frames per second";
js_StringTable['NO_LOAD'] = "Nothing to load";

js_StringTable["REF_PHYS"] = "Ref. Phys. Name";
js_StringTable["ACC_NUM"] = "Accession number";
js_StringTable["MODALITY"] = "Modality";
js_StringTable["IMG_COUNT"] = "Images";
js_StringTable["SR_REPORTS"] = "SR Reports";
js_StringTable["PDF_DOCS"] = "PDF Documents";
js_StringTable["OPEN_LE"] = "Expert mode";
js_StringTable["LOAD_TIP"] = "The list of studies found on this media follows. Click the <span class=\"action show selected\"></span> icon in order to load the related images";

js_StringTable["ZOOM_TIP"] = "Zoom image"; // action.imageToolAssocZoomToMouseWheel.name
js_StringTable["SELSTACK_TIP"] = "Select/Stack image"; // tool.SelectStack.name
js_StringTable["PAN_TIP"] = "Pan image"; // tool.Pan.name
js_StringTable["WINLEV_TIP"] = "Window / Level";
js_StringTable["MEAS_TIP"]  = "Measurements";
js_StringTable["MEAS_LINE_TIP"]  = "Measure distance"; // action.imageToolAssocMeasDistanceToLeftMouseBtn.name
js_StringTable["MEAS_RECT_TIP"]  = "Measure rect area"; // action.imageToolAssocMeasAreaToRightMouseBtn.name
js_StringTable["MEAS_ELLIPT_TIP"]  = "Measure ellipt area"; // action.imageToolAssocMeasAreaEllipseToRightMouseBtn.name
js_StringTable["RESET_TIP"]  = "Reset"; // tool.windowLevel.resetWinCaption
js_StringTable["NEXT_SERIES_TIP"]  = "Next series"; // action.navigateNextSeries.shortDescr
js_StringTable["PREV_SERIES_TIP"]  = "Previous series"; // action.navigatePreviousSeries.shortDescr
js_StringTable["PREV_IMG_TIP"]  = "Previous frame"; // action.navigatePreviousFrame.shortDescr
js_StringTable["NEXT_IMG_TIP"]  = "Next frame"; // action.navigateNextFrame.shortDescr
js_StringTable["SERIE_THUM_TIP"]  = "Series thumbnails"; // action.navigateNextFrame.shortDescr
js_StringTable["LAYOUT_TIP"]  = "Set display mode"; // action.displayMode.shortDescr
js_StringTable["OVERLAYS_TIP"] = "Overlays"; // dispSettingsFrame.overlaysPrefs
js_StringTable["OVERLAY_TIP"] = "Overlay"; // dispSettingsFrame.overlaysPrefs
js_StringTable["REF_LINES_TIP"] = "Reference lines"; // action.imageToggleFirstLastRefLines.name
js_StringTable["STUDY_TIME"] = "Study time";
js_StringTable["DESCRIPTION"] = "Description"; // winLevelPresetsFrame.presetDescr
js_StringTable["WINLEVELPRESET"] = "Window/Level presets"; // winLevelPresetsFrame.frameTitle
js_StringTable["WINWIDTH"] = "Window width"; // winLevelPresetsFrame.presetWinWidth
js_StringTable["WINLEV"] = "Window level"; // winLevelPresetsFrame.presetWinCenter
js_StringTable["ADDWINLEVELPRESET"] = "Add Window/Level presets"; 
js_StringTable["WINLEVPRESERROR"] = "Configuration error";
js_StringTable["WINLEVSAMEDESCR"] = "A Window/Level preset with the same description is already present";
js_StringTable["WININVALID"] = "Invalid window width";
js_StringTable["LEVINVALID"] = "Invalid window level";
js_StringTable["PREFERENCES"] = "Preferences";
js_StringTable["HIPPI_CANVAS"] = "Enable high resolution series panels (when supported by the device)";
js_StringTable["FORCE_CINE"] = "Cine playback functions (series)";
js_StringTable["ROTATE_COUNTER_CLOCKWISE"] = "Rotate the panel of 90 degrees counter clockwise";
js_StringTable["ROTATE_CLOCKWISE"] = "Rotate the panel of 90 degrees clockwise";
js_StringTable["FLIP_V"] = "Flip the panel vertically";
js_StringTable["FLIP_H"] = "Flip the panel horizontally";
js_StringTable["OPEN_ALL"] = "Open everything";
js_StringTable["SIZES_DETECTOR"] = "SIZES ARE AT DETECTOR - APPROX"; // textOverlay.filmLikeSizesLabel
js_StringTable["SIZES_CALIBRATED"] = "SIZES CALIBRATED - APPROX"; // textOverlay.dicomCalibrSizesLabel
js_StringTable["USG_NOT_ALLOWED"] = "You are not allowed to use the software.\nConcurrent users limit reached."; //err.dlg.licenseErr.msg
js_StringTable["DISTANCE"] = "Distance";
js_StringTable["AREA"] = "Area";
js_StringTable["EXP_DROP"] = "Share study through Dropbox";
js_StringTable["EXP_DROP_POP"] = "Share this study with a remote recipient! <br/>(e.g. for remote consultation, second opinion, etc.)";
js_StringTable["EXP_DROP_HINT"] = "Thanks to this feature, sharing the images of a study with a remote recipient (e.g., for a consultation, second opinion, etc.) is fast, easy and secure.";
js_StringTable["EXP_DROP_EXPMODE"] = "To use this feature, swith to expert mode";
js_StringTable["LOCALEYE_LAUNCH_FILE"] = "Please double click the file %1 located in the root of the media";
js_StringTable["SHRE_YOUR_EXAM"] = "Share you exam!";
js_StringTable["LE_FILE_PREFIX"] = "View";
js_StringTable["PERIMETER"] = "Perimeter";
js_StringTable["MIN"] = "Min.";
js_StringTable["MEDIA"] = "Mean";
js_StringTable["MAX"] = "Max.";
js_StringTable["STD_DEV"] = "Std. deviation";
js_StringTable["MEAS_DENS_TIP"] = "Measure density";
js_StringTable["STUDY_COMMENTS"] = "Study comments";
js_StringTable["WARNING"] = "Warning";
js_StringTable["WARN_POPUP_BLOCKED"] = "Your browser blocked the RemotEye Lite attempt of opening the file.";
js_StringTable["WARN_POPUP_SOLUTION_A"] = "Update your browser's settings or click";
js_StringTable["WARN_POPUP_SOLUTION_B"] = "to open the file manually.";
js_StringTable["DISMISS"] = "Dismiss";
js_StringTable["HERE"] = "here";
js_StringTable["LOGIN_BUTTON"] = "Login";
js_StringTable["LOGIN_BUTTON_WORKING"] = "Please wait...";
js_StringTable["SLICE_THICK"] = "Slice thickness";
js_StringTable["MEAS_ANGLE_TIP"] = "Measure angle";
js_StringTable["ANGLE"] = "Angle";
js_StringTable["ENCAP_PDF"] = "DICOM Encapsulated PDF";
js_StringTable["DICOM_SR"] = "DICOM Structured Report";
js_StringTable["DBL_CLICK_OPEN"] = "(double click or long press to open)";
js_StringTable["MAGNIFIER_TIP"] = "Magnifier";
js_StringTable["VIEW_REPORT"] = "View report..."; //action.reportingViewReport.shortDescr
js_StringTable["NO_REPORT_FOUND"] = "No report found for the current study";
js_StringTable["REPORTS"] = "Reports";
js_StringTable["WARN_DECODING_ERRORS"] = "Warning, RemotEye Lite encountered some issues while decoding files of the exam";
js_StringTable["INVERT_IMAGE"] = "Invert image";
js_StringTable["LE_IS_STARTING"] = "LocalEye Viewer is currently loading, it will start in a few seconds";
js_StringTable["PATIENT_ID"] = "Patient ID";
js_StringTable["PWD_EXPIRED_TITLE"] = "Password Expired"; // authentication.passwordExpiredTitle
js_StringTable["PWD_EXPIRED_MSG"] = "The current password has expired. Please update your login data"; // authentication.passwordExpiredMsg 
js_StringTable["OLD_PWD"] = "Old password"; // authentication.oldPassword 
js_StringTable["NEW_PWD"] = "New password"; // authentication.newPassword 
js_StringTable["NEW_PWD_CONFIRM"] = "New password (confirm)"; // authentication.newPasswordConfirm
js_StringTable["UPDATE_PWD"] = "Update password"; // authentication.updatePassword
js_StringTable["CHANGE_PWD"] = "Change password"; // authentication.changePassword
js_StringTable["AUTO_LOGOFF_DLG_TITLE"]= "Automatic logoff";
js_StringTable["AUTO_LOGOFF_MSG1"] =  "You are going to be automatically logged off soon due to inactivity.";
js_StringTable["AUTO_LOGOFF_MSG2"] =  "Move the mouse or touch the screen in order to avoid being automatically logged off.";
js_StringTable["AUTO_LOGOFF_COUNTER"] =  "Automatic logoff in";
js_StringTable["LOGGEDOFF_MSG"] =  "Logged off due to inactivity.";
js_StringTable["SECONDS"] =  "seconds";
js_StringTable["SHOW_NON_DICOM_FILES"] = "Show other files/reports";
js_StringTable["CLOSE"] = "Close";