js_StringTable = new Array();

js_StringTable["ACTIONS_TITLE"] = "Azioni";
js_StringTable["SEARCH"] = "Trova";
js_StringTable["SEARCH_H"] = "Cerca studi nel backend remoto";
js_StringTable["SETTINGS"] = "Configurazione di base";
js_StringTable["SETTINGS_H"] = "Configura alcuni elementi base";
js_StringTable["ABOUT"] = "Info";
js_StringTable["ABOUT_H"] = "Informazioni su RemotEye Lite";
js_StringTable["ABOUT_DEV"] = "Sviluppato da NeoLogica";
js_StringTable["READ_BEF_USE"] = "Leggere il Manuale Utente prima dell'uso.";
js_StringTable["BACK"] = "Indietro";
js_StringTable["FIND_PAGE_TITLE"] = "Studi";
js_StringTable["SHOW_FILTER"] = "Visualizza filtri";
js_StringTable["STUDIES_FOUND"] = "Pagina";
js_StringTable["PATIENT_NAME"] = "Nome paziente";
js_StringTable["STUDY_DATE"] = "Data studio";
js_StringTable["STUDY_DESCR"] = "Descr. studio";
js_StringTable["SERIES_FOUND"] = "Serie trovate";
js_StringTable["SERIES_DESCR"] = "Descr. serie";
js_StringTable["PATIENT_SEX"] = "Sesso";
js_StringTable["PATIENT_BD"] = "Data di nascita";
js_StringTable["NUM_OF_FRAME"] = "Number of frames";
js_StringTable["STUDY_DATE_START"] = "Esaminato dopo";
js_StringTable["STUDY_DATE_END"] = "Esaminato prima";
js_StringTable["PANELS_LAYOUT"] = "Layout dei pannelli";
js_StringTable["ROWS"] = "Righe";
js_StringTable["COLS"] = "Colonne";
js_StringTable["CANCEL"] = "Annulla";
js_StringTable["SAVE"] = "Salva";
js_StringTable["ACCEPT"] = "Accetta";
js_StringTable["PREVIOUS"] = "Precedente";
js_StringTable["NEXT"] = "Successivo";
js_StringTable["TODAY"] = "Oggi";
js_StringTable["LAST_WEEK"] = "Ultimi 7 giorni";
js_StringTable["LAST_MONTH"] = "Ultimo mese";
js_StringTable["WHENEVER"] = "Qualsiasi data";

js_StringTable["DISCLAIMER"] = "Questo modulo software NON è concepito per un utilizzo diagnostico.";
js_StringTable["INV_LIC"] = "Licenza non valida";
js_StringTable["COMM_ERR"] = "Errore di comunicazione";
js_StringTable["INV_LOG"] = "Login invalido";

js_StringTable['DEF_FPS'] = "Frames al secondo";
js_StringTable['NO_LOAD'] = "Niente da caricare";

js_StringTable["REF_PHYS"] = "Ref. Phys. Name";
js_StringTable["ACC_NUM"] = "Accession number";
js_StringTable["MODALITY"] = "Modalità";
js_StringTable["IMG_COUNT"] = "Immagini";
js_StringTable["SR_REPORTS"] = "Refert SR";
js_StringTable["PDF_DOCS"] = "Documenti PDF";
js_StringTable["OPEN_LE"] = "Modalità esperta";
js_StringTable["LOAD_TIP"] = "Di seguito è riportata la lista degli studi presenti su questo supporto. <br/>Ogni studio presenta l'icona <span class=\"action show selected\"></span> da cliccare al fine di visualizzare le sue immagini.";

js_StringTable["ZOOM_TIP"] = "Zoom immagine"; // action.imageToolAssocZoomToMouseWheel.name
js_StringTable["SELSTACK_TIP"] = "Seleziona / Scorri immagine"; // tool.SelectStack.name
js_StringTable["PAN_TIP"] = "Sposta immagine"; // tool.Pan.name
js_StringTable["WINLEV_TIP"] = "Window / Level";
js_StringTable["MEAS_TIP"]  = "Misura";
js_StringTable["MEAS_LINE_TIP"]  = "Misura distanza"; // action.imageToolAssocMeasDistanceToLeftMouseBtn.name
js_StringTable["MEAS_RECT_TIP"]  = "Misura area rettangolare"; // action.imageToolAssocMeasAreaToRightMouseBtn.name
js_StringTable["MEAS_ELLIPT_TIP"]  = "Misura area ellittica"; // action.imageToolAssocMeasAreaEllipseToRightMouseBtn.name
js_StringTable["RESET_TIP"]  = "Reset"; // tool.windowLevel.resetWinCaption
js_StringTable["NEXT_SERIES_TIP"]  = "Serie successiva"; // action.navigateNextSeries.shortDescr
js_StringTable["PREV_SERIES_TIP"]  = "Serie precedente"; // action.navigatePreviousSeries.shortDescr
js_StringTable["PREV_IMG_TIP"]  = "Frame precedente"; // action.navigatePreviousFrame.shortDescr
js_StringTable["NEXT_IMG_TIP"]  = "Frame successivo"; // action.navigateNextFrame.shortDescr
js_StringTable["SERIE_THUM_TIP"]  = "Anteprime serie"; // action.navigateNextFrame.shortDescr
js_StringTable["LAYOUT_TIP"]  = "Set display mode"; // action.displayMode.shortDescr
js_StringTable["OVERLAYS_TIP"] = "Overlays"; // dispSettingsFrame.overlaysPrefs
js_StringTable["OVERLAY_TIP"] = "Overlay"; // dispSettingsFrame.overlaysPrefs
js_StringTable["REF_LINES_TIP"] = "Reference lines"; // action.imageToggleFirstLastRefLines.name
js_StringTable["STUDY_TIME"] = "Ora";
js_StringTable["DESCRIPTION"] = "Descrizione"; // winLevelPresetsFrame.presetDescr
js_StringTable["WINLEVELPRESET"] = "Preselezioni Window/Level"; // winLevelPresetsFrame.frameTitle
js_StringTable["WINWIDTH"] = "Window width"; // winLevelPresetsFrame.presetWinWidth
js_StringTable["WINLEV"] = "Window level"; // winLevelPresetsFrame.presetWinCenter
js_StringTable["ADDWINLEVELPRESET"] = "Aggiungi Window/Level";
js_StringTable["WINLEVPRESERROR"] = "Errore nella configurazione";
js_StringTable["WINLEVSAMEDESCR"] = "E' già presente una preselezione Window/Level con la stessa descrizione";
js_StringTable["WININVALID"] = "Window width invalido";
js_StringTable["LEVINVALID"] = "Window level invalido";
js_StringTable["PREFERENCES"] = "Preferenze";
js_StringTable["HIPPI_CANVAS"] = "Abilita i pannelli per le serie ad alta definizione (quando supportato dal device)";
js_StringTable["FORCE_CINE"] = "Funzioni di riproduzione sequenze cine (serie)";
js_StringTable["ROTATE_COUNTER_CLOCKWISE"] = "Ruota il pannello di 90 gradi in senso anti-orario";
js_StringTable["ROTATE_CLOCKWISE"] = "Routa il pannello di 90 gradi in senso orario";
js_StringTable["FLIP_V"] = "Ribalta l'immagine verticalmente";
js_StringTable["FLIP_H"] = "Ribalta l'immagine orizzontalmente";
js_StringTable["OPEN_ALL"] = "Apri tutto";
js_StringTable["SIZES_DETECTOR"] = "MISURAZ. COME SU FILM - APPROX"; // textOverlay.filmLikeSizesLabel
js_StringTable["SIZES_CALIBRATED"] = "MISURAZ. CALIBRATE - APPROX"; // textOverlay.dicomCalibrSizesLabel
js_StringTable["USG_NOT_ALLOWED"] = "Non siete autorizzati ad usare il software.\nIl limite delle licenze \u00e8 stato superato."; //err.dlg.licenseErr.msg
js_StringTable["DISTANCE"] = "Distanza";
js_StringTable["AREA"] = "Area";
js_StringTable["EXP_DROP"] = "Condividi lo studio attraverso Dropbox"; // action.shareStudyThroughDropbox.shortDescr
js_StringTable["EXP_DROP_POP"] = "Condividi questo studio con un destinatario remoto!<br/>(es. per consultazione remota, seconda opinione, ecc.)"; // share.throughDropbox.balloon
js_StringTable["EXP_DROP_HINT"] = "Grazie a questa funzionalità, condividere le immagini di uno studio con un destinatario remoto (es. per consultazione remota, seconda opinione, ecc.) è veloce, facile e sicuro."; // share.throughDropbox.howItWorksExpl
js_StringTable["EXP_DROP_EXPMODE"] = "Per utilizzare la funzionalità usa la modalità esperta"; 
js_StringTable["LOCALEYE_LAUNCH_FILE"] = "Fai doppio click sul file %1 che troverai nella cartella principale del supporto";
js_StringTable["SHRE_YOUR_EXAM"] = "Condividi il tuo esame!";
js_StringTable["LE_FILE_PREFIX"] = "Apri";
js_StringTable["PERIMETER"] = "Perimetro";
js_StringTable["MIN"] = "Min.";
js_StringTable["MEDIA"] = "Media";
js_StringTable["MAX"] = "Max.";
js_StringTable["STD_DEV"] = "Std. deviation";
js_StringTable["MEAS_DENS_TIP"] = "Misura densità";
js_StringTable["STUDY_COMMENTS"] = "Commenti dello studio";
js_StringTable["WARNING"] = "Attenzione";
js_StringTable["WARN_POPUP_BLOCKED"] = "Il browser ha bloccato il tentativo di apertura del file tramite popup.";
js_StringTable["WARN_POPUP_SOLUTION_A"] = "Si consiglia di aggiornare le impostazioni del browser, in alternativa clicca ";
js_StringTable["WARN_POPUP_SOLUTION_B"] = "per aprire il file."
js_StringTable["DISMISS"] = "Chiudi";
js_StringTable["HERE"] = "qui";
js_StringTable["LOGIN_BUTTON"] = "Login";
js_StringTable["LOGIN_BUTTON_WORKING"] = "Attendere prego...";
js_StringTable["SLICE_THICK"] = "Slice thickness";
js_StringTable["MEAS_ANGLE_TIP"] = "Misura angolo";
js_StringTable["ANGLE"] = "Angolo";
js_StringTable["ENCAP_PDF"] = "DICOM Encapsulated PDF";
js_StringTable["DICOM_SR"] = "DICOM Structured Report";
js_StringTable["DBL_CLICK_OPEN"] = "(doppio click o tocco prolungato per aprire)";
js_StringTable["MAGNIFIER_TIP"] = "Lente d'ingrandimento";
js_StringTable["VIEW_REPORT"] = "Visualizza referto..."; //action.reportingViewReport.shortDescr
js_StringTable["NO_REPORT_FOUND"] = "Non è stato trovato alcun referto per questo studio";
js_StringTable["REPORTS"] = "Referti";
js_StringTable["WARN_DECODING_ERRORS"] = "Attenzione, RemotEye Lite ha riscontrato degli errori nel decodificare alcuni file";
js_StringTable["INVERT_IMAGE"] = "Inverti immagine";
js_StringTable["LE_IS_STARTING"] = "LocalEye Viewer è in fase di caricamento, verrà visualizzato tra qualche secondo";
js_StringTable["PATIENT_ID"] = "ID paziente";
js_StringTable["PWD_EXPIRED_TITLE"] = "Password scaduta"; // authentication.passwordExpiredTitle
js_StringTable["PWD_EXPIRED_MSG"] = "La password è scaduta. Si prega di aggiornarla"; // authentication.passwordExpiredMsg 
js_StringTable["OLD_PWD"] =  "Vecchia password";
js_StringTable["NEW_PWD"] =  "Nuova password";
js_StringTable["NEW_PWD_CONFIRM"] =  "Nuova password (ripeti)";
js_StringTable["UPDATE_PWD"] =  "Aggiorna password";
js_StringTable["CHANGE_PWD"] =  "Modifica password";
js_StringTable["AUTO_LOGOFF_DLG_TITLE"]= "Disconnessione automatica";
js_StringTable["AUTO_LOGOFF_MSG1"] =  "Inutilizzo del software rilevato, a breve verrà automaticamente disconnesso.";
js_StringTable["AUTO_LOGOFF_MSG2"] =  "Muovere il mouse o toccare lo schermo per evitare la disconnessione automatica.";
js_StringTable["AUTO_LOGOFF_COUNTER"] =  "Disconnessione in";
js_StringTable["LOGGEDOFF_MSG"] =  "Disconnesso per inutilizzo del software.";
js_StringTable["SECONDS"] =  "secondi";
js_StringTable["SHOW_NON_DICOM_FILES"] = "Visualizza altri files/referti";
js_StringTable["CLOSE"] = "Chiudi";